


eureka:
  instance:
    instance-id: eureka-service2
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #注册到注册中心
      defaultZone: http://localhost:9001/eureka/


spring:
  application:
    name: eureka-service2
server:
  port: 8002